### ISSUE TITLE
Twilio Auth Token incorrectly failing regex check

### ISSUE THREAD

**Issue by dgduncan** [twilio-labs/twilio-firebase-extensions#13]
Using firebase-tools version 9.22.0, twilio auth token check can not be correctly passed. Valid twilio token fails check, along with other generated examples of 32 char tokens a-f 0-9.

**Comment by dgduncan** [comment]
After further investigation, the secret value is being created in Secret Engine even though the check is failing in the CLI

<img width="955" alt="Screen Shot 2021-11-13 at 1 51 38 PM" src="https://user-images.githubusercontent.com/10761062/141655815-f0c6fd47-9fb8-4707-9f41-c9e32edc282e.png">

**Comment by philnash** [comment]
Hey @dgduncan, thanks for the report. That is odd behaviour indeed. Can you share a screenshot of it not working too? I think this may be something I'll need to take up with Firebase.

**Comment by dgduncan** [comment]
Attempting to add token and it failing

<img width="1276" alt="Screen Shot 2021-11-14 at 8 14 10 PM" src="https://user-images.githubusercontent.com/10761062/141707687-53f461f9-96a7-4895-8a49-0b63b0f1d160.png">

Token is added and exists in Secret Engine even though CLI rejects.

<img width="594" alt="Screen Shot 2021-11-14 at 8 16 31 PM" src="https://user-images.githubusercontent.com/10761062/141707723-de1c4492-e633-4aae-afce-7ef254c8ee17.png">

Token matches regex check

<img width="601" alt="Screen Shot 2021-11-14 at 8 16 38 PM" src="https://user-images.githubusercontent.com/10761062/141707748-d3c523e5-8434-420c-8569-e1d53d557bed.png">

**Comment by philnash** [comment]
I think I've spotted the issue in the firebase-tools project. Will fork and try to fix it. Thanks for your help!

**Comment by i14h** [comment]
@joehan fyi

**Comment by dgduncan** [comment]
Glad to help. Cheers!

**Comment by philnash** [comment]
PR submitted to firebase-tools: https://github.com/firebase/firebase-tools/pull/3901
