### ISSUE TITLE
Installation using Firebase console results in "Unknown error has occurred"

### ISSUE THREAD

**Issue by TheAussieStew** [twilio-labs/twilio-firebase-extensions#14]
I'm currently trying to install the "Send Messages with Twilio" extension here: https://firebase.google.com/products/extensions/twilio-send-message

When I enter in this information:

<img width="562" alt="image" src="https://user-images.githubusercontent.com/28683089/142086045-0dba7909-0491-4478-82b7-09a5d39a3c28.png">

In these forms (deliberately omitting the optional fields here):

<img width="567" alt="image" src="https://user-images.githubusercontent.com/28683089/142086181-463abd10-30c4-44f1-8e54-bb051c799359.png">

I get this error:

<img width="843" alt="image" src="https://user-images.githubusercontent.com/28683089/142086204-24a81614-29a0-4c70-a874-ba83de63fcfb.png">

In the console log I get these errors too:

<img width="500" alt="image" src="https://user-images.githubusercontent.com/28683089/142086256-9828622c-f0a2-4bf3-a893-cbde051d9ab3.png">

Any ideas on what could be causing this problem? I'm currently trying to install it using the firebase-tools cli instead of the GUI console.

EDIT: I've tried installing it using the same credentials I used for the GUI console, but this time using the Firebase CLI and I get this error:

Error: HTTP Error: 400, Secret ID `{same secret as shown above}` is invalid, must be of form `projects/*/secrets/*/versions/*`

**Comment by philnash** [comment]
I have no idea what's going on here. Are you able to install other extensions at all?

The CLI may not help as that [has other problems at the moment](https://github.com/twilio-labs/twilio-firebase-extensions/issues/13).

**Comment by TheAussieStew** [comment]
Hi @philnash, is there something I can clarify about the issue? I've tried another extension called "Delete User Data", which works fine.  

The first screenshot is of the Twilio dashboard, which has the credentials necessary to install the extension. The second screenshot is of the Firebase extension flow, found [here](https://firebase.google.com/products/extensions/twilio-send-message).

**Comment by philnash** [comment]
Argh, I just tried this and found that the issue seems to be the same validation issue that the CLI is facing.

I will follow up with Firebase about this. Sorry!

**Comment by TheAussieStew** [comment]
No problem at all, appreciate the speedy responses!

**Comment by i14h** [comment]
Sorry guys, @pavelgj is working on a fix and we'll release an update soon!

**Comment by TheAussieStew** [comment]
Appreciate it guys! In the meantime, is there some kind of workaround I can apply? Otherwise, happy to wait for the fix

**Comment by i14h** [comment]
Unfortunately not yet. There's something we need to fix on our side. I'll keep you posted!

**Comment by pavelgj** [comment]
Sorry folks, it appears there's a bug with secrets validation in the backend. The only workaround at the moment is to remove `validationRegex` from `extension.yaml` and republish.

**Comment by philnash** [comment]
I have disabled validation for the secrets in the extensions. @TheAussieStew you should be able to install version 0.1.1 of the Send Message extension from the console now.

**Comment by TheAussieStew** [comment]
Thank you, the installation works now.
