### ISSUE TITLE
SMS API - Message formatting

### ISSUE THREAD

**Issue by debungle-it** [twilio-labs/twilio-firebase-extensions#22]
Hi Twilio,

I am looking for ways to perform basic formatting in the messages sent via SMS by Twilio. Escape sequences like "\n" are translated into "\\n", as I was told by your support team.

New line and hyperlinks would be great to have.

**Comment by philnash** [comment]
In an SMS you cannot hyperlink regular text, you just have to send the URL in the message itself. Mobile device SMS applications will display the URL as a link.

To use new lines, you don't need to use an escape sequence, you can use the new line character. For example, when using the Firebase plugin, store the body of the message in the collection like:

```js
admin.firestore().collection('messages').add({
  to: '+15551234567',
  body: `Hello from Firebase!

This is on a new line!`
});
```

**Comment by philnash** [comment]
Hey @debungle-it, did you find that you were able to send messages with newlines with my example? Can I close this issue? Thanks!

**Comment by philnash** [comment]
I’m going to close this now. Please do let me know if there is still an issue.
