### ISSUE TITLE
WhatsApp limit messages per second

### ISSUE THREAD

**Issue by NashIlli** [twilio-labs/twilio-firebase-extensions#24]
Hello! How many messages can I send per second using this extension?

Thanks a lot!

**Comment by philnash** [comment]
Hey @NashIlli, the limits on messages per second are not set by the extension, but by Twilio. [From the documentation](https://www.twilio.com/docs/whatsapp/best-practices-and-faqs):

> The WhatsApp Business API with Twilio has a maximum messaging throughput of 25 MPS (messages per second) per sender for outbound traffic containing text-only. The maximum throughput for outbound traffic containing media files is 1.5 MPS.

There is more detail in [the documentation](https://www.twilio.com/docs/whatsapp/best-practices-and-faqs). 

Do note, WhatsApp also enforces daily rate limits depending on the tier you are currently in. Please read this article on [WhatsApp rate limits](https://support.twilio.com/hc/en-us/articles/360024008153-WhatsApp-Rate-Limiting) for more detail.
