### ISSUE TITLE
meta field is always "unauthorized"

### ISSUE THREAD

**Issue by saifylis21** [twilio-labs/twilio-firebase-extensions#26]
Hi there!

<img width="321" alt="Screenshot 2022-06-11 at 1 55 50 PM" src="https://user-images.githubusercontent.com/64803110/173181149-74bea73e-9f65-44be-85bb-a140719f6348.png">

As shown in the image, my meta fields always show a "unauthorized" and "ERROR". I can't seem to understand why? Because the SendGrid API key can been given full access as well.

**Comment by saifylis21** [comment]
Nvm, it was the wrong API key. Sorry :')

**Comment by philnash** [comment]
Glad you worked it out!
