### ISSUE TITLE
Email not received from SendGrid

### ISSUE THREAD

**Issue by saifylis21** [twilio-labs/twilio-firebase-extensions#27]
I am using "Sync Contacts with SendGrid" extension from firebase. After I insert a new document with an email field in the 'contacts' collection; it creates a new field called meta with it's state sub-field being set to SUCCESS (see the image attached).

<img width="442" alt="Screenshot 2022-06-12 at 8 35 27 PM" src="https://user-images.githubusercontent.com/64803110/173241534-edf0dec0-8eee-4154-9821-ed9541c349e5.png">

This indicates that the email (saifsadiq.ss@gmail.com) has been sent the SendGrid template successfully. However, after checking everywhere in my mail, I did not received it. This only worked once for this particular email but for some reason has stopped working receiving now. Does this mean SendGrid cannot resend another mail to an already used/sent email address? Any help and support would be much appreciated, thanks!

**Comment by philnash** [comment]
The Sync Contacts with SendGrid extension does not send emails. It only [adds the contact to your marketing campaigns list](https://docs.sendgrid.com/api-reference/contacts/add-or-update-a-contact).

I'm not sure why you were expecting an email to be sent, or why one was sent in the first place? Do you have an automation set up for your marketing campaigns contacts?
