### ISSUE TITLE
Invalid statusCallback URL

### ISSUE THREAD

**Issue by ewenmic** [twilio-labs/twilio-firebase-extensions#50]
A malformed statusCallback endpoint is included in the payload generated by the processQueue function from https://extensions.dev/extensions/twilio/send-message

This results in errors in the twilio dashboard, and no webhook events being ingested. 

processQueue passes 'statusCallback' to the getFunctionsUrl utils method which creates a URL like the following:
https://us-central1-MYPROJECT.cloudfunctions.net/statusCallback

When the extension is installed through the firebase marketplace, it appends an extension instance ID to the function name. This defaults to 'ext-send-message', but is initially configurable (to allow for multiple extension installations).  This is the endpoint where the statusCallback actually deployed. 
https://us-central1-MYPROJECT.cloudfunctions.net/ext-send-message-statusCallback

**Comment by tbondar** [comment]
Same problem here. It would be nice to see it fixed.

**Comment by KishoreNodejs** [comment]
yeah is this ryt..check statusCallback.js in your google cloud console function edit then look up the line no 17

const url = (0, utils_1.getFunctionsUrl)("statusCallback");

im not sure you can change" statusCallback" to "ext-send-message-statusCallback"

**Comment by gfielding** [comment]
Any updates on this? It's causing https://www.twilio.com/docs/api/errors/11200 errors for us.

**Comment by josefhalcombPBE** [comment]
Same here, getting [https://www.twilio.com/docs/api/errors/11200](https://www.twilio.com/docs/api/errors/11200) errors and need a fix.

**Comment by jakehockey10** [comment]
Anyone know of a work around?  The activity on this repo seems to have slowed way down... :(

**Comment by druv5319** [comment]
Fixed #101
