### ISSUE TITLE
Update to at least node.js 18

### ISSUE THREAD

**Issue by smacksocialdev** [twilio-labs/twilio-firebase-extensions#83]
Node.js 16 and below are being deprecated on January 30, 2024 and this extension currently utilizes node.js 14.

statusCallback and processQueue currently use node.js 14, they should be updated to node.js 18.

**Comment by Georg7** [comment]
+1 This is critical. I'm using this extension in production. Please don't make me regret it.

**Comment by druv5319** [comment]
Fixed #101 

New version is currently in the review process by the Firebase team; should be on the extensions marketplace within a few days. If you'd like to install before then, you can use this link: https://console.firebase.google.com/project/_/extensions/install?ref=twilio/send-message@0.3.4 or use `firebase ext:install twilio/send-message@0.3.4`.
